name: WispRandomPotionEffect
version: 1.0-SNAPSHOT
main: dev.yhdiamond.wisprandompotioneffect.WispRandomPotionEffect
api-version: 1.16
commands:
  wisprandompotioneffects:
    usage: /wisprandompotioneffects <start/stop>
    description: A command to start the Wisp Random Potion Effects challenge
